replicaCount: 1

namespace: development

image:
  repository: nginx
  pullPolicy: IfNotPresent

containerPort: 80
service:
  type: ClusterIP
  port: 80

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"